# Target the built-in AT Translated Set 2 keyboard.
[ids]
0001:0001:093d12dc

# keyd detects the physical Nitro key as F16.
# F24 is intentionally used as the KDE-visible shortcut key.
[main]
f16 = f24
